# Einsum Practice

In [1]:
import numpy as np

In [4]:
a = np.ones((5,3))

In [8]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.random.randint(1, 100, (5,10,10))

In [17]:
b

array([[[ 9, 53, 97,  8, 84, 91, 26, 24, 83, 49],
        [40, 46, 43, 79, 46, 39, 58,  1, 69, 38],
        [20, 13, 28, 85, 79, 40, 91, 83, 10, 12],
        [60, 91, 53, 56, 65, 48,  1, 10, 54, 48],
        [65, 54, 55, 57, 62, 26, 23, 83, 23, 19],
        [56, 96, 54, 19, 42, 43, 50, 96, 69, 95],
        [47, 86, 21, 78, 73, 50, 87, 25, 51, 86],
        [43, 55,  5, 58, 53, 49,  9, 23, 88, 42],
        [44, 70, 41, 69, 54, 10, 40, 40, 29, 47],
        [10, 82,  3, 83, 40, 23,  8, 87, 40, 53]],

       [[ 1,  7, 26, 67, 56, 99, 65, 37, 51, 73],
        [73, 59, 32, 66, 77, 40, 63,  3, 54, 12],
        [71, 97, 68, 84, 77, 29, 47, 39,  5, 55],
        [52, 22, 48, 21, 85, 30, 14, 80, 42, 67],
        [66,  5, 95, 62, 35, 60, 43, 98, 11, 82],
        [65, 22, 17,  2, 56, 56, 17, 53, 73, 55],
        [63, 58, 34, 41, 46, 49, 90, 49, 87, 61],
        [61, 86,  4, 37, 44, 76, 55, 47, 50, 90],
        [41, 75, 33, 73, 96, 61, 97, 63,  9, 20],
        [40, 15, 93, 94, 23, 29, 98, 72, 52, 67]

In [9]:
c = np.einsum("ij,ik->jk",a,b)

In [10]:
c

array([[290., 194., 228., 252., 291., 140., 385., 283., 251., 358.],
       [290., 194., 228., 252., 291., 140., 385., 283., 251., 358.],
       [290., 194., 228., 252., 291., 140., 385., 283., 251., 358.]])

In [12]:
np.transpose(a)@b

array([[290., 194., 228., 252., 291., 140., 385., 283., 251., 358.],
       [290., 194., 228., 252., 291., 140., 385., 283., 251., 358.],
       [290., 194., 228., 252., 291., 140., 385., 283., 251., 358.]])

In [21]:
cbatch = np.einsum("ij,ikb->jkb",a,b)

In [22]:
cbatch

array([[[249., 205., 235., 156., 285., 391., 217., 186., 239., 284.],
        [237., 285., 218., 352., 337., 229., 223., 241., 292., 192.],
        [230., 302., 243., 339., 341., 255., 328., 239., 114., 183.],
        [288., 257., 125., 242., 350., 293., 167., 204., 230., 233.],
        [282., 210., 335., 251., 282., 224., 252., 392., 250., 224.],
        [294., 263., 260.,  87., 296., 319., 184., 328., 421., 217.],
        [278., 271., 186., 181., 242., 267., 258., 222., 265., 363.],
        [227., 332., 161., 239., 339., 279., 259., 226., 221., 292.],
        [157., 290., 200., 310., 290., 213., 319., 254., 223., 272.],
        [202., 263., 250., 383., 229., 211., 228., 322., 274., 326.]],

       [[249., 205., 235., 156., 285., 391., 217., 186., 239., 284.],
        [237., 285., 218., 352., 337., 229., 223., 241., 292., 192.],
        [230., 302., 243., 339., 341., 255., 328., 239., 114., 183.],
        [288., 257., 125., 242., 350., 293., 167., 204., 230., 233.],
        [282., 210

In [19]:
b.shape

(5, 10, 10)

In [20]:
a.shape

(5, 3)